# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leastSqr.ui'
#
# Created: Thu May 22 17:47:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1240, 882)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/icon.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 236), stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(:/new/prefix1/47766.png);\n"
"background-image: url(:/new/prefix1/E:/BACKUP/photos n vids/HD WALLPAPERS/47766.jpg);\n"
"border-bottom-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 55), stop:1 rgba(198, 198, 198, 97));\n"
"\n"
"\n"
" QPushButton {pressed {image: url(:/new/prefix1/47766.png);}}"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 311, 801))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(59, 59, 59, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.tabWidget.setIconSize(QtCore.QSize(20, 23))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ControlTab = QtGui.QWidget()
        self.ControlTab.setObjectName(_fromUtf8("ControlTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.ControlTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeObs = QtGui.QTreeWidget(self.ControlTab)
        self.treeObs.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.988636, y2:0, stop:0 rgba(164, 164, 164, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.treeObs.setObjectName(_fromUtf8("treeObs"))
        self.gridLayout_2.addWidget(self.treeObs, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getObsButton = QtGui.QCommandLinkButton(self.ControlTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getObsButton.sizePolicy().hasHeightForWidth())
        self.getObsButton.setSizePolicy(sizePolicy)
        self.getObsButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.getObsButton.setAutoFillBackground(False)
        self.getObsButton.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.getObsButton.setObjectName(_fromUtf8("getObsButton"))
        self.horizontalLayout.addWidget(self.getObsButton)
        self.updateObs = QtGui.QPushButton(self.ControlTab)
        self.updateObs.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.updateObs.setObjectName(_fromUtf8("updateObs"))
        self.horizontalLayout.addWidget(self.updateObs)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ControlTab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.getControlButton = QtGui.QCommandLinkButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getControlButton.sizePolicy().hasHeightForWidth())
        self.getControlButton.setSizePolicy(sizePolicy)
        self.getControlButton.setAutoFillBackground(False)
        self.getControlButton.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.getControlButton.setObjectName(_fromUtf8("getControlButton"))
        self.horizontalLayout_4.addWidget(self.getControlButton)
        self.updateControl = QtGui.QPushButton(self.tab)
        self.updateControl.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.updateControl.setObjectName(_fromUtf8("updateControl"))
        self.horizontalLayout_4.addWidget(self.updateControl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.treeControl = QtGui.QTreeWidget(self.tab)
        self.treeControl.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.988636, y2:0, stop:0 rgba(164, 164, 164, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.treeControl.setObjectName(_fromUtf8("treeControl"))
        self.verticalLayout_6.addWidget(self.treeControl)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.ProvisTab = QtGui.QWidget()
        self.ProvisTab.setObjectName(_fromUtf8("ProvisTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ProvisTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.CalcProvisionals = QtGui.QCommandLinkButton(self.ProvisTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalcProvisionals.sizePolicy().hasHeightForWidth())
        self.CalcProvisionals.setSizePolicy(sizePolicy)
        self.CalcProvisionals.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.CalcProvisionals.setObjectName(_fromUtf8("CalcProvisionals"))
        self.horizontalLayout_3.addWidget(self.CalcProvisionals)
        self.saveProvisButton = QtGui.QPushButton(self.ProvisTab)
        self.saveProvisButton.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.saveProvisButton.setObjectName(_fromUtf8("saveProvisButton"))
        self.horizontalLayout_3.addWidget(self.saveProvisButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.treeProvis = QtGui.QTreeWidget(self.ProvisTab)
        self.treeProvis.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.988636, y2:0, stop:0 rgba(164, 164, 164, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.treeProvis.setObjectName(_fromUtf8("treeProvis"))
        self.gridLayout_3.addWidget(self.treeProvis, 4, 0, 1, 1)
        self.tabWidget.addTab(self.ProvisTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(399, 9, 2, 2))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 0, 1171, 851))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AngsanaUPC"))
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(_fromUtf8("\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(57, 57, 57, 102), stop:1 rgba(255, 255, 255, 255));\n"
"image: url(:/new/prefix1/coollogo_com-267102207.png);"))
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setLineWidth(10)
        self.label.setText(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.solveButton = QtGui.QPushButton(self.centralwidget)
        self.solveButton.setGeometry(QtCore.QRect(1070, 460, 161, 23))
        self.solveButton.setStyleSheet(_fromUtf8(" QPushButton:pressed {background-image: url(:/new/prefix1/47766.png);}\n"
""))
        self.solveButton.setObjectName(_fromUtf8("solveButton"))
        self.graph = QtGui.QWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(320, 10, 751, 601))
        self.graph.setAutoFillBackground(False)
        self.graph.setStyleSheet(_fromUtf8("background-image: url(:/newPrefix/back.bmp);"))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1110, 360, 81, 19))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rod"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(1080, 300, 151, 22))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gridLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.iterationLine = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.iterationLine.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.iterationLine.setObjectName(_fromUtf8("iterationLine"))
        self.verticalLayout_3.addWidget(self.iterationLine)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1070, 380, 161, 71))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 161, 71))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.distanceLine = QtGui.QLineEdit(self.gridLayoutWidget)
        self.distanceLine.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.distanceLine.setObjectName(_fromUtf8("distanceLine"))
        self.gridLayout_4.addWidget(self.distanceLine, 1, 1, 1, 1)
        self.directionLine = QtGui.QLineEdit(self.gridLayoutWidget)
        self.directionLine.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.directionLine.setObjectName(_fromUtf8("directionLine"))
        self.gridLayout_4.addWidget(self.directionLine, 2, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe Script"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe Script"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.ControlButton = QtGui.QPushButton(self.centralwidget)
        self.ControlButton.setGeometry(QtCore.QRect(1080, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.ControlButton.setFont(font)
        self.ControlButton.setObjectName(_fromUtf8("ControlButton"))
        self.scaleDial = QtGui.QDial(self.centralwidget)
        self.scaleDial.setGeometry(QtCore.QRect(1090, 40, 61, 91))
        self.scaleDial.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.scaleDial.setMouseTracking(True)
        self.scaleDial.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.scaleDial.setMaximum(20)
        self.scaleDial.setObjectName(_fromUtf8("scaleDial"))
        self.zoom = QtGui.QSlider(self.centralwidget)
        self.zoom.setGeometry(QtCore.QRect(1110, 130, 21, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom.sizePolicy().hasHeightForWidth())
        self.zoom.setSizePolicy(sizePolicy)
        self.zoom.setMouseTracking(True)
        self.zoom.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.zoom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zoom.setMinimum(-10)
        self.zoom.setMaximum(20)
        self.zoom.setSingleStep(1)
        self.zoom.setPageStep(1)
        self.zoom.setProperty("value", 1)
        self.zoom.setSliderPosition(1)
        self.zoom.setTracking(False)
        self.zoom.setOrientation(QtCore.Qt.Vertical)
        self.zoom.setInvertedAppearance(True)
        self.zoom.setInvertedControls(True)
        self.zoom.setObjectName(_fromUtf8("zoom"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(320, 620, 911, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setIconSize(QtCore.QSize(48, 48))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.stdDevTree = QtGui.QTreeWidget(self.tab_2)
        self.stdDevTree.setGeometry(QtCore.QRect(10, 10, 431, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdDevTree.sizePolicy().hasHeightForWidth())
        self.stdDevTree.setSizePolicy(sizePolicy)
        self.stdDevTree.setObjectName(_fromUtf8("stdDevTree"))
        self.stdDevTree.header().setHighlightSections(False)
        self.stdDevTree.header().setMinimumSectionSize(31)
        self.stdDevTree.header().setSortIndicatorShown(False)
        self.stdDevTree.header().setStretchLastSection(False)
        self.glocheckLabel = QtGui.QLabel(self.tab_2)
        self.glocheckLabel.setGeometry(QtCore.QRect(450, 30, 151, 21))
        self.glocheckLabel.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(0, 153, 0, 176), stop:1 rgba(255, 255, 255, 255));"))
        self.glocheckLabel.setObjectName(_fromUtf8("glocheckLabel"))
        self.numcheckLabel = QtGui.QLabel(self.tab_2)
        self.numcheckLabel.setGeometry(QtCore.QRect(450, 10, 151, 21))
        self.numcheckLabel.setStyleSheet(_fromUtf8("\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(0, 153, 0, 111), stop:1 rgba(255, 255, 255, 255));"))
        self.numcheckLabel.setObjectName(_fromUtf8("numcheckLabel"))
        self.vtpvLabel = QtGui.QLabel(self.tab_2)
        self.vtpvLabel.setGeometry(QtCore.QRect(450, 80, 151, 21))
        self.vtpvLabel.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.vtpvLabel.setObjectName(_fromUtf8("vtpvLabel"))
        self.posteriori = QtGui.QLabel(self.tab_2)
        self.posteriori.setGeometry(QtCore.QRect(450, 100, 151, 21))
        self.posteriori.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.posteriori.setObjectName(_fromUtf8("posteriori"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.posteriori_2 = QtGui.QLabel(self.tab_3)
        self.posteriori_2.setGeometry(QtCore.QRect(460, 80, 61, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posteriori_2.sizePolicy().hasHeightForWidth())
        self.posteriori_2.setSizePolicy(sizePolicy)
        self.posteriori_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.posteriori_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.posteriori_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posteriori_2.setObjectName(_fromUtf8("posteriori_2"))
        self.cofactorAObs = QtGui.QTableWidget(self.tab_3)
        self.cofactorAObs.setGeometry(QtCore.QRect(520, 0, 341, 181))
        self.cofactorAObs.setObjectName(_fromUtf8("cofactorAObs"))
        self.cofactorAObs.setColumnCount(0)
        self.cofactorAObs.setRowCount(0)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(430, 30, 51, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(860, 10, 51, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(72)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.stdDevAtree = QtGui.QTreeWidget(self.tab_3)
        self.stdDevAtree.setGeometry(QtCore.QRect(10, 10, 421, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdDevAtree.sizePolicy().hasHeightForWidth())
        self.stdDevAtree.setSizePolicy(sizePolicy)
        self.stdDevAtree.setObjectName(_fromUtf8("stdDevAtree"))
        self.stdDevAtree.header().setHighlightSections(False)
        self.stdDevAtree.header().setMinimumSectionSize(31)
        self.stdDevAtree.header().setSortIndicatorShown(False)
        self.stdDevAtree.header().setStretchLastSection(False)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.stdDevObsTree = QtGui.QTreeWidget(self.tab_4)
        self.stdDevObsTree.setGeometry(QtCore.QRect(10, 10, 421, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdDevObsTree.sizePolicy().hasHeightForWidth())
        self.stdDevObsTree.setSizePolicy(sizePolicy)
        self.stdDevObsTree.setObjectName(_fromUtf8("stdDevObsTree"))
        self.stdDevObsTree.header().setHighlightSections(False)
        self.stdDevObsTree.header().setMinimumSectionSize(31)
        self.stdDevObsTree.header().setSortIndicatorShown(False)
        self.stdDevObsTree.header().setStretchLastSection(False)
        self.cofactorZ = QtGui.QTableWidget(self.tab_4)
        self.cofactorZ.setGeometry(QtCore.QRect(480, 0, 371, 181))
        self.cofactorZ.setObjectName(_fromUtf8("cofactorZ"))
        self.cofactorZ.setColumnCount(0)
        self.cofactorZ.setRowCount(0)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(430, 10, 51, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(72)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(850, 10, 51, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Mincho"))
        font.setPointSize(72)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1080, 280, 151, 19))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 1.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.RepeatSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.238636, QtGui.QColor(198, 198, 198, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Rod"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1160, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1160, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.helpButton = QtGui.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1070, 481, 161, 131))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.nodeg = QtGui.QPushButton(self.frame_2)
        self.nodeg.setStyleSheet(_fromUtf8("border-color: rgb(255, 0, 0);\n"
"color: rgb(255, 0, 0);"))
        self.nodeg.setObjectName(_fromUtf8("nodeg"))
        self.verticalLayout_5.addWidget(self.nodeg)
        self.showObsBut = QtGui.QPushButton(self.frame_2)
        self.showObsBut.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.showObsBut.setObjectName(_fromUtf8("showObsBut"))
        self.verticalLayout_5.addWidget(self.showObsBut)
        self.bowditch = QtGui.QPushButton(self.frame_2)
        self.bowditch.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.bowditch.setObjectName(_fromUtf8("bowditch"))
        self.verticalLayout_5.addWidget(self.bowditch)
        self.saveAll = QtGui.QPushButton(self.frame_2)
        self.saveAll.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0.238636 rgba(198, 198, 198, 0), stop:1 rgba(255, 255, 255, 255));"))
        self.saveAll.setObjectName(_fromUtf8("saveAll"))
        self.verticalLayout_5.addWidget(self.saveAll)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.treeObs.headerItem().setText(0, _translate("MainWindow", "Setup", None))
        self.treeObs.headerItem().setText(1, _translate("MainWindow", "Observed", None))
        self.treeObs.headerItem().setText(2, _translate("MainWindow", "Direction", None))
        self.treeObs.headerItem().setText(3, _translate("MainWindow", "Distance", None))
        self.getObsButton.setText(_translate("MainWindow", "GET OBSERVATIONS", None))
        self.updateObs.setText(_translate("MainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ControlTab), _translate("MainWindow", "OBSERVATIONS", None))
        self.getControlButton.setText(_translate("MainWindow", "GET CONTROL POINTS", None))
        self.updateControl.setText(_translate("MainWindow", "Update", None))
        self.treeControl.headerItem().setText(0, _translate("MainWindow", "Name", None))
        self.treeControl.headerItem().setText(1, _translate("MainWindow", "Y", None))
        self.treeControl.headerItem().setText(2, _translate("MainWindow", "X", None))
        self.treeControl.headerItem().setText(3, _translate("MainWindow", "Z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CONTROL", None))
        self.CalcProvisionals.setText(_translate("MainWindow", "CALCULATE PROVISIONAL", None))
        self.saveProvisButton.setText(_translate("MainWindow", "SAVE TO FILE", None))
        self.treeProvis.headerItem().setText(0, _translate("MainWindow", "Name", None))
        self.treeProvis.headerItem().setText(1, _translate("MainWindow", "Y", None))
        self.treeProvis.headerItem().setText(2, _translate("MainWindow", "X", None))
        self.treeProvis.headerItem().setText(3, _translate("MainWindow", "Z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ProvisTab), _translate("MainWindow", "Provisional", None))
        self.solveButton.setText(_translate("MainWindow", "SOLVE", None))
        self.label_6.setText(_translate("MainWindow", "Weights", None))
        self.iterationLine.setText(_translate("MainWindow", "5", None))
        self.distanceLine.setText(_translate("MainWindow", "40000", None))
        self.directionLine.setText(_translate("MainWindow", "0.25", None))
        self.label_9.setText(_translate("MainWindow", "Distances :", None))
        self.label_8.setText(_translate("MainWindow", "Directions :", None))
        self.ControlButton.setText(_translate("MainWindow", "Show/Hide Control", None))
        self.stdDevTree.headerItem().setText(0, _translate("MainWindow", "name", None))
        self.stdDevTree.headerItem().setText(1, _translate("MainWindow", "std. Dev X", None))
        self.stdDevTree.headerItem().setText(2, _translate("MainWindow", "std. Dev Y", None))
        self.stdDevTree.headerItem().setText(3, _translate("MainWindow", "std. Dev Z", None))
        self.glocheckLabel.setText(_translate("MainWindow", "GLOBAL CHECK SUCCESS", None))
        self.numcheckLabel.setText(_translate("MainWindow", "NUMERICAL CHECK SUCCESS", None))
        self.vtpvLabel.setText(_translate("MainWindow", "VTPV", None))
        self.posteriori.setText(_translate("MainWindow", "Posteriori", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Std Deviations of Unknowns", None))
        self.posteriori_2.setText(_translate("MainWindow", "Posteriori .", None))
        self.label_2.setText(_translate("MainWindow", "(cofocator insight:)", None))
        self.label_3.setText(_translate("MainWindow", "(", None))
        self.label_4.setText(_translate("MainWindow", ")", None))
        self.stdDevAtree.headerItem().setText(0, _translate("MainWindow", "Adjusted Obs", None))
        self.stdDevAtree.headerItem().setText(1, _translate("MainWindow", "std. Dev ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Std deviations of Adj. Observations", None))
        self.stdDevObsTree.headerItem().setText(0, _translate("MainWindow", "Observation", None))
        self.stdDevObsTree.headerItem().setText(1, _translate("MainWindow", "std. Dev ", None))
        self.label_5.setText(_translate("MainWindow", "(", None))
        self.label_10.setText(_translate("MainWindow", ")", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Std Deviations of Residuals", None))
        self.label_7.setText(_translate("MainWindow", "Iterations", None))
        self.label_11.setText(_translate("MainWindow", " ZOOM", None))
        self.label_12.setText(_translate("MainWindow", " Error E Resize", None))
        self.helpButton.setText(_translate("MainWindow", "HELP", None))
        self.nodeg.setText(_translate("MainWindow", "NO DEGREES OF FREEDOM", None))
        self.showObsBut.setText(_translate("MainWindow", "SHOW OBSERVATIONS", None))
        self.bowditch.setText(_translate("MainWindow", "SAVE BOWDITCH", None))
        self.saveAll.setText(_translate("MainWindow", "SAVE ADJUSTMENT FILE", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As.", None))

import Resource_rc
